### ISSUE TITLE
考察一下Travis

### ISSUE THREAD

**Issue by EthanLin-TWer** [linesh-simplicity/translation-spring-mvc-4-documentation#21]
### Steps
- [x] Have basic environment setup(npm, node, etc)
  - basically just specify node version in `.travis.yml` file and npm is provided by travis by default
- [x] Install dependencies through npm command line
  - install gitbook-cli globally in the travis `before_install` stage
- [x] Build deployable book structure using `gitbook build`
- [x] Setup encrypted AK/SK into Travis and access in scripts
- [x] Upload built book directories to Qiniu
### Pros
- 界面更美腻
- 刚好学习一下其他的CI
- 在线pipeline
### Cons
- PK&SK放到网上似乎不安全

**Comment by xcatliu** [comment]
Travis 有 encrypt api 应该可以解决 PK&SK 的安全问题

**Comment by EthanLin-TWer** [comment]
哇哦，看起来不错，我来试试~

**Comment by EthanLin-TWer** [comment]
@xcatliu Hi，我已经把自动化构建搬到travis上啦，谢谢你的更新 👍 

看了你的github，也有一个在进行的翻译项目，管理什么的有很多值得我借鉴的呢。棒棒的。

**Comment by xcatliu** [comment]
@linesh-simplicity 哇效率真高！相互学习哈~

**Comment by EthanLin-TWer** [comment]
把你加到contributor list 里面去了哈哈哈
