### ISSUE TITLE
README 中的即时评论链接有问题

### ISSUE THREAD

**Issue by xcatliu** [linesh-simplicity/translation-spring-mvc-4-documentation#23]
> [在文档上进行即时评论](http://mvc.linesh.tw/)：在gitbook文档上，鼠标划过任何段落右侧，浮现+号时点击即可评论

这个链接链到了 qiniu 的页面里，which donot have the feature.

BTW，我觉得这个即时评论功能有些鸡肋，而且设计得很不人性化，对一句话的评论，居然可以有很多个主题，每个主题里面又有很多评论。这样的二级评论在这里太重了。

**Comment by EthanLin-TWer** [comment]
Temporary 我把[在文档上进行即时评论](#)的链接指向了gitbook上。

太“重”，不知道是怎样的感觉？目前我所理解的重，可能会是讨论本身过多的展开，为主要文本带来噪音，影响阅读体验？

一开始能想象的使用场景，是就翻译本身展开的讨论，此时即时评论更多是一种讨论的功能，使读者与译者有机会得以交流。翻得好，翻的不好，有地方表达交流。

其他类型的反馈或疑惑，在解决以后就关闭了。还是带有个人口味。
