### ISSUE TITLE
spring web flow特性第三条的建议

### ISSUE THREAD

**Issue by pollyduan** [linesh-simplicity/translation-spring-mvc-4-documentation#24]
翻译的很好，从头开始看，流畅不反感。
文章开始 spring web flow特性的第三条，我看没有完整翻译，以下是我的一点建议，供参考。

web flow是mvc的一个扩展，有点类似于工作流，用以实现类似向导来完成一个web事务。那么这一段这样翻译如何？投票。

原文：
SWF allows you to capture logical page flows as self-contained modules that are reusable in different situations, and as such is ideal for building web application modules that guide the user through controlled navigations that drive business processes.

译文：
SWF 允许你将一些有逻辑的页面流抓取为一些独立的模块，在不同的情况下重用，这在构建引导用户凭借导航来推动业务处理的情形下是完美的解决方案。

**Comment by EthanLin-TWer** [comment]
谢谢你的肯定和反馈~

诶，这句真是神级翻译了，我之前翻的时候就感觉找不到好的翻法，现在一看，依然觉得蛮难。嗯嗯，我觉得你的译文把“在不同的情况下重用”这个地方断个小句挺好的，比较有中文的感觉，而且关键的词也都有译到，不足是后面“这在构建引导用户……的情形下”这部分有点绕，不是很容易看明白词间的关联，“构建”似乎少了宾语？

controlled navigation，我理解的是，因为页面的导航是必须经过web flow后端的（有一个executeParameter参数），因此用户无法通过浏览器随意前进后退，而必须通过页面上的按钮或其他方式向后端发送页面跳转的请求。因此说navigation是被control的，即页面跳转流程和逻辑是被预定义和限制的。不过我没想好怎么翻，“凭借导航”似乎稍欠此层的意思。

that drive business processes，我理解它是修饰前面的controlled navigation，这个预定义的页面跳转导航，恰好反映的就是业务流程（比如一个保险流程，必须先填被保人的信息、被保物的信息，然后才能看到保费和其他信息，才能进一步支付。这个流程不可逆，必须前面的完成才能到达后面的流程，这种业务流程非常严格的情形使用web flow来体现到技术流程/页面流程上就比较适合），因此说通过web flow或controlled navigation来驱动或体现业务流程，“推动业务处理”的译文也没有体现出这层意思，可能“驱动/体现业务流程”会更好一些。

希望我说的有帮助，有兴趣的话可以再看看哦，有什么想法随时讨论~

**Comment by pollyduan** [comment]
你说的很对，呵呵，controlled这个过去式忽略了，应该是个adj，语言上我还查的远，呵呵，只是抛砖引玉。我绕晕了。

**Comment by EthanLin-TWer** [comment]
啊，不客气，语言上我也很不够，相互学习！
