### ISSUE TITLE
在大陆地区无法访问

### ISSUE THREAD

**Issue by yuzhiping** [linesh-simplicity/translation-spring-mvc-4-documentation#30]
在大陆地区无法访问，[主站](mvc.linesh.tw)，使用VPN也不行，解析不到这个域名，是不是换地址了？

**Comment by cdtian** [comment]
没问题哈 
https://linesh.gitbooks.io/spring-mvc-documentation-linesh-translation/content/


唯一区别我这hosts替换爬到墙外了


------------------ 原始邮件 ------------------
发件人: "hexsmith";<notifications@github.com>;
发送时间: 2017年3月7日(星期二) 上午10:15
收件人: "linesh-simplicity/translation-spring-mvc-4-documentation"<translation-spring-mvc-4-documentation@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [linesh-simplicity/translation-spring-mvc-4-documentation] 在大陆地区无法访问 (#30)




在大陆地区无法访问，主站，使用VPN也不行，解析不到这个域名，是不是换地址了？

**Comment by cdtian** [comment]
sorry 没仔细看你的问题 ,那个域名应该挂了 我刚才给你地址没问题




------------------ 原始邮件 ------------------
发件人: "hexsmith";<notifications@github.com>;
发送时间: 2017年3月7日(星期二) 上午10:15
收件人: "linesh-simplicity/translation-spring-mvc-4-documentation"<translation-spring-mvc-4-documentation@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [linesh-simplicity/translation-spring-mvc-4-documentation] 在大陆地区无法访问 (#30)




在大陆地区无法访问，主站，使用VPN也不行，解析不到这个域名，是不是换地址了？

**Comment by yuzhiping** [comment]
@costtian [https://linesh.gitbooks.io/spring-mvc-documentation-linesh-translation/content/](https://linesh.gitbooks.io/spring-mvc-documentation-linesh-translation/content/)这个地址可以访问

**Comment by EthanLin-TWer** [comment]
抱歉，我应该更新一下 README 文档，或者把 `mvc.linesh.tw`  这个主站移除。

主站放在七牛上，因为域名没有备案不让我使用，备案起来似乎还比较麻烦，我就暂时还没做。

gitbook 的链接是可以访问的，麻烦暂时先用这个哈，虽然长些，看起来也不是很爽。

感谢两位提 issue 和热心解答。

**Comment by wizardforcel** [comment]
@cdtian `hosts`如何替换泛域名解析`*.gitbooks.io`？
