### ISSUE TITLE
主站挂了嘤嘤嘤

### ISSUE THREAD

**Issue by Zijianlalala** [linesh-simplicity/translation-spring-mvc-4-documentation#32]

**Comment by EthanLin-TWer** [comment]
诶呀，这个七牛云现在要求实名登记备案了。虽然说这个个人信息也是泄露得差不多了，但我就是迟迟不想去搞啊😂

**Comment by EthanLin-TWer** [comment]
重新配置了一下 DNS，现在这里可以访问了：https://spring-mvc.linesh.tw 。暂时是直接指向了 Gitbook，可能速度会稍微慢一点。

是因为七牛云的测试域名政策做了更严格的限制，估计是被干掉了。
